export const SOCIAL_MEDIA_LINKS = [
    { name: "Facebook", icon: "fa-brands fa-facebook", url: "https://www.facebook.com/MillerCustomCues/" },
    { name: "Instagram", icon: "fa-brands fa-instagram", url: "https://www.instagram.com/jmillercustomcues/" },
    { name: "Bluesky", icon: "fa-brands fa-bluesky", url: "https://www.bsky.social/jmillercustomcues/" }
];

export const CUE_BASIC_MATERIAL_OPTIONS = [
    { guid: 'Juma', commonName: 'Juma' },
    { guid: 'Black Juma', commonName: 'Black Juma' },
    { guid: 'Other', commonName: 'Other' },
];

export const COLOR_OPTIONS = [
    { value: 'Black', label: 'Black' },
    { value: 'Blue', label: 'Blue' },
    { value: 'Brown', label: 'Brown' },
    { value: 'Green', label: 'Green' },
    { value: 'Grey', label: 'Grey' },
    { value: 'Orange', label: 'Orange' },
    { value: 'Pink', label: 'Pink' },
    { value: 'Purple', label: 'Purple' },
    { value: 'Red', label: 'Red' },
    { value: 'White', label: 'White' },
    { value: 'Yellow', label: 'Yellow' }
];

export const METAPHYSICAL_OPTIONS = [
    { value: 'none', label: 'Not yet available. Currently being researched' },
    { value: 'ambition', label: 'Ambition' },
    { value: 'balance', label: 'Balance' },
    { value: 'beauty', label: 'Beauty' },
    { value: 'calming', label: 'Calming' },
    { value: 'clarity', label: 'Clarity' },
    { value: 'concentration', label: 'Concentration' },
    { value: 'confidence', label: 'Confidence' },
    { value: 'connectedness', label: 'Connectedness' },
    { value: 'control', label: 'Control' },
    { value: 'creativity', label: 'Creativity' },
    { value: 'energy', label: 'Energy' },
    { value: 'focus', label: 'Focus' },
    { value: 'grounding', label: 'Grounding' },
    { value: 'growth', label: 'Growth' },
    { value: 'harmony', label: 'Harmony' },
    { value: 'healing', label: 'Healing' },
    { value: 'imagination', label: 'Imagination' },
    { value: 'insight', label: 'Insight' },
    { value: 'inspiration', label: 'Inspiration' },
    { value: 'integrity', label: 'Integrity' },
    { value: 'intuition', label: 'Intuition' },
    { value: 'kindness', label: 'Kindness' },
    { value: 'knowledge', label: 'Knowledge' },
    { value: 'logic', label: 'Logic' },
    { value: 'love', label: 'Love' },
    { value: 'loyalty', label: 'Loyalty' },
    { value: 'new_beginnings', label: 'New Beginnings' },
    { value: 'peace', label: 'Peace' },
    { value: 'positive_luck', label: 'Positive Luck' },
    { value: 'power', label: 'Power' },
    { value: 'precision', label: 'Precision' },
    { value: 'protection', label: 'Protection' },
    { value: 'purity', label: 'Purity' },
    { value: 'resilience', label: 'Resilience' },
    { value: 'spiritual_guidance', label: 'Spiritual Guidance' },
    { value: 'spiritual_amplification', label: 'Spiritual Amplification' },
    { value: 'strength', label: 'Strength' },
    { value: 'wisdom', label: 'Wisdom' }
];

export const STATUS_OPTIONS_AVAILABLE = [
    { label: 'Available' },
    { label: 'Not Available' }
];

export const STATUS_OPTIONS_CUE = [
    ...STATUS_OPTIONS_AVAILABLE,
    { label: 'Sold' },
    { label: 'Coming Soon' }
];

export const TIP_SIZE_OPTIONS = [
    { value: '11.8', label: '11.8' },
    { value: '12', label: '12' },
    { value: '12.2', label: '12.2' },
    { value: '12.4', label: '12.4' },
    { value: '12.6', label: '12.6' },
    { value: '12.8', label: '12.8' },
    { value: '13', label: '13' },
    { value: '14', label: '14' },
    { value: 'other', label: 'Other' }
];

export const SHAFT_MATERIAL_OPTIONS = [
    { value: 'hard_maple', label: 'Hard Maple' },
    { value: 'roasted_maple', label: 'Roasted Maple' },
    { value: 'kielwood', label: 'Kielwood' },
    { value: 'curly_kielwood', label: 'Curly Kielwood' },
    { value: 'purpleheart', label: 'Purpleheart' },
    { value: 'carbon_fiber', label: 'Carbon Fiber' }
];

export const SHAFT_TAPER_OPTIONS = [
    { value: 'pro_taper', label: 'Pro-Taper' },
    { value: 'break_jump', label: 'Break / Jump' },
    { value: 'carom', label: 'Carom' }
];

export const JOINT_PIN_SIZE_OPTIONS = [
    { value: '3_8_10_mod', label: '3/8-10 in Modified' },
    { value: '3_8_10', label: '3/8-10 in' },
    { value: '5_16_14', label: '5/16-14 in' },
    { value: '5_16_18', label: '5/16-18 in' },
    { value: 'american_ball', label: 'American Ball Thread / Radial' },
    { value: 'wavy', label: 'Wavy' },
    { value: 'quick_release', label: 'Quick Release' },
    { value: 'uni_loc', label: 'Uni-Loc' },
    { value: 'other', label: 'Other' }
];

export const JOINT_MATERIAL_OPTIONS = [
    { value: 'stainless_steel', label: 'Stainless Steel' },
    { value: 'aluminum', label: 'Aluminum' },
    { value: 'titanium', label: 'Titanium' },
    { value: 'brass', label: 'Brass' },
    { value: 'g10', label: 'G10' }
];

export const WRAP_TYPE_OPTIONS = [
    { value: 'irish_linen', label: 'Irish Linen' },
    { value: 'leather', label: 'Leather' },
    { value: 'embossed_leather', label: 'Embossed Leather' },
    { value: 'stacked_leather', label: 'Stacked Leather' },
    { value: 'other', label: 'Other' }
];

export const BASIC_SIZE_OPTIONS = [
    { value: 'small', label: 'Small / Extra-Small' },
    { value: 'medium', label: 'Medium' },
    { value: 'large', label: 'Large' },
    { value: 'extra_large', label: 'Extra Large' },
    { value: 'complex', label: 'Complex' },
    { value: 'multi', label: 'Multi-color/-mat\'l' }
];

export const PSYCHOLOGICAL_CORRESPONDENCE_OPTIONS = [
    { value: 'abundance', label: 'Abundance' },
    { value: 'acceptance', label: 'Acceptance' },
    { value: 'achievement', label: 'Achievement' },
    { value: 'alleviates_sorrow', label: 'Alleviates Sorrow' },
    { value: 'ambition', label: 'Ambition' },
    { value: 'assertiveness', label: 'Assertiveness' },
    { value: 'attracts_new_love', label: 'Attracts New Love' },
    { value: 'attracts_prosperity', label: 'Attracts Prosperity' },
    { value: 'awareness', label: 'Awareness' },
    { value: 'awakenings', label: 'Awakenings' },
    { value: 'balance', label: 'Balance' },
    { value: 'balanced_judgement', label: 'Balanced Judgement' },
    { value: 'benevolence', label: 'Benevolence' },
    { value: 'bliss', label: 'Bliss' },
    { value: 'business_booster', label: 'Business Booster' },
    { value: 'calmness', label: 'Calmness' },
    { value: 'change', label: 'Change' },
    { value: 'changes_for_success', label: 'Changes for Success' },
    { value: 'charisma', label: 'Charisma' },
    { value: 'clarity', label: 'Clarity' },
    { value: 'communication', label: 'Communication' },
    { value: 'compassion', label: 'Compassion' },
    { value: 'concentration', label: 'Concentration' },
    { value: 'confidence', label: 'Confidence' },
    { value: 'contentment', label: 'Contentment' },
    { value: 'control', label: 'Control' },
    { value: 'courage', label: 'Courage' },
    { value: 'creating_positivity', label: 'Creating Positivity' },
    { value: 'creativity', label: 'Creativity' },
    { value: 'decision_making', label: 'Decision-Making' },
    { value: 'deeper_self_awareness', label: 'Deeper Self-Awareness' },
    { value: 'determination', label: 'Determination' },
    { value: 'diplomacy', label: 'Diplomacy' },
    { value: 'drive', label: 'Drive' },
    { value: 'emotional_balance', label: 'Emotional Balance' },
    { value: 'emotional_ease', label: 'Emotional Ease' },
    { value: 'emotional_healing', label: 'Emotional Healing' },
    { value: 'emotional_honesty', label: 'Emotional Honesty' },
    { value: 'emotional_mastery', label: 'Emotional Mastery' },
    { value: 'emotional_security', label: 'Emotional Security' },
    { value: 'emotional_strength', label: 'Emotional Strength' },
    { value: 'empathy', label: 'Empathy' },
    { value: 'empowerment', label: 'Empowerment' },
    { value: 'endurance', label: 'Endurance' },
    { value: 'enlightenment', label: 'Enlightenment' },
    { value: 'enthusiasm', label: 'Enthusiasm' },
    { value: 'fast_acting_love', label: 'Fast-Acting Love Attractor' },
    { value: 'fast_progress', label: 'Fast Progress toward Success' },
    { value: 'fearlessness', label: 'Fearlessness' },
    { value: 'feminine_vitality', label: 'Feminine Vitality' },
    { value: 'fidelity', label: 'Fidelity' },
    { value: 'fine_tuned_perception', label: 'Fine-Tuned Perception' },
    { value: 'flexibility', label: 'Flexibility' },
    { value: 'focus', label: 'Focus' },
    { value: 'forgiveness', label: 'Forgiveness' },
    { value: 'fortitude', label: 'Fortitude' },
    { value: 'freedom_from_expectations', label: 'Freedom from Expectations' },
    { value: 'generosity', label: 'Generosity' },
    { value: 'getting_what_you_desire', label: 'Getting what you Desire' },
    { value: 'good_decision_making', label: 'Good Decision-Making' },
    { value: 'good_fortune', label: 'Good Fortune' },
    { value: 'good_luck', label: 'Good Luck' },
    { value: 'good_will', label: 'Good Will' },
    { value: 'grounding', label: 'Grounding' },
    { value: 'growth', label: 'Growth' },
    { value: 'harmony', label: 'Harmony' },
    { value: 'harmonious_relations', label: 'Harmonious Relations' },
    { value: 'heals_heartbreak', label: 'Heals Heartbreak' },
    { value: 'healing', label: 'Healing' },
    { value: 'holistic_balance', label: 'Holistic Balance' },
    { value: 'holistic_well_being', label: 'Holistic Well-Being' },
    { value: 'honesty', label: 'Honesty' },
    { value: 'imagination', label: 'Imagination' },
    { value: 'inner_peace', label: 'Inner Peace' },
    { value: 'insight', label: 'Insight' },
    { value: 'inspiration', label: 'Inspiration' },
    { value: 'integrity', label: 'Integrity' },
    { value: 'intellectual_acumen', label: 'Intellectual Acumen' },
    { value: 'intellectual_power', label: 'Intellectual Power' },
    { value: 'intuition', label: 'Intuition' },
    { value: 'joy', label: 'Joy' },
    { value: 'letting_go', label: 'Letting Go' },
    { value: 'loving_communication', label: 'Loving Communication' },
    { value: 'luck', label: 'Luck' },
    { value: 'magical_well_being', label: 'Magical Well-Being' },
    { value: 'magnet_for_love', label: 'Magnet for Love' },
    { value: 'manifesting_intentions', label: 'Manifesting Intentions' },
    { value: 'manifests_desire', label: 'Manifests Desire' },
    { value: 'motivation', label: 'Motivation' },
    { value: 'new_beginnings', label: 'New Beginnings' },
    { value: 'new_romance', label: 'New Romance' },
    { value: 'non_judgemental_love', label: 'Non-Judgemental Love & Acceptance' },
    { value: 'objectivity', label: 'Objectivity' },
    { value: 'optimism', label: 'Optimism' },
    { value: 'originality', label: 'Originality' },
    { value: 'passion', label: 'Passion' },
    { value: 'patience', label: 'Patience' },
    { value: 'peace', label: 'Peace' },
    { value: 'perception', label: 'Perception' },
    { value: 'personal_freedom', label: 'Personal Freedom' },
    { value: 'personal_growth', label: 'Personal Growth' },
    { value: 'positive_attitude', label: 'Positive Attitude' },
    { value: 'positive_change', label: 'Positive Change' },
    { value: 'positive_romantic_change', label: 'Positive Romantic Change' },
    { value: 'positivity', label: 'Positivity' },
    { value: 'potent_success', label: 'Potent Success' },
    { value: 'progress', label: 'Progress' },
    { value: 'protection', label: 'Protection' },
    { value: 'protects_from_anger', label: 'Protects from Other\'s Anger' },
    { value: 'rationality', label: 'Rationality' },
    { value: 'realism', label: 'Realism' },
    { value: 'reliable_perception', label: 'Reliable Perception' },
    { value: 'self_assurance', label: 'Self-Assurance' },
    { value: 'self_awareness', label: 'Self-Awareness' },
    { value: 'self_belief', label: 'Self-Belief' },
    { value: 'self_confidence', label: 'Self-Confidence' },
    { value: 'self_control', label: 'Self-Control' },
    { value: 'self_esteem', label: 'Self-Esteem' },
    { value: 'self_expression', label: 'Self-Expression' },
    { value: 'self_love', label: 'Self-Love' },
    { value: 'self_reliance', label: 'Self-Reliance' },
    { value: 'self_respect', label: 'Self-Respect' },
    { value: 'self_value', label: 'Self-Value' },
    { value: 'self_worth', label: 'Self-Worth' },
    { value: 'serenity', label: 'Serenity' },
    { value: 'sexual_excitement', label: 'Sexual Excitement' },
    { value: 'sexual_self_reflection', label: 'Sexual Self-Reflection' },
    { value: 'sharp_mind', label: 'Sharp Mind' },
    { value: 'sociability', label: 'Sociability' },
    { value: 'soul_attraction', label: 'Soul Attraction' },
    { value: 'spiritual_growth', label: 'Spiritual Growth' },
    { value: 'spiritual_love', label: 'Spiritual Love' },
    { value: 'spontaneity', label: 'Spontaneity' },
    { value: 'stability', label: 'Stability' },
    { value: 'stone_to_sell_success', label: 'Stone to "Sell Your Success"' },
    { value: 'strength', label: 'Strength' },
    { value: 'strength_of_mind', label: 'Strength of Mind' },
    { value: 'stress_reduction', label: 'Stress-Reduction' },
    { value: 'stress_relief', label: 'Stress-Relief' },
    { value: 'success', label: 'Success' },
    { value: 'synchronicity', label: 'Synchronicity' },
    { value: 'tenacity', label: 'Tenacity' },
    { value: 'togetherness', label: 'Togetherness' },
    { value: 'tolerance', label: 'Tolerance' },
    { value: 'transformation', label: 'Transformation' },
    { value: 'trust', label: 'Trust' },
    { value: 'trusting_instincts', label: 'Trusting Instincts' },
    { value: 'truth', label: 'Truth' },
    { value: 'unconditional_love', label: 'Unconditional Love' },
    { value: 'understanding', label: 'Understanding' },
    { value: 'uplifts', label: 'Uplifts' },
    { value: 'vitality', label: 'Vitality' },
    { value: 'will', label: 'Will' },
    { value: 'willpower', label: 'Willpower' },
    { value: 'zesty_for_living', label: 'Zesty for Living' }
];

export const CRYSTAL_CATEGORY_OPTIONS = [
    { value: 'abundance_good_fortune', label: 'For Abundance & Good Fortune' },
    { value: 'love', label: 'For Love' },
    { value: 'success', label: 'For Success' },
    { value: 'well_being', label: 'For Well-Being' }
];

export const IRISH_LINEN_COLOR_OPTIONS = [
    { value: 'black', label: 'Black' },
    { value: 'black_w_blue', label: 'Black w/ Blue' },
    { value: 'black_w_dbl_wht', label: 'Black w/ Dbl Wht' },
    { value: 'black_w_green', label: 'Black w/ Green' },
    { value: 'black_w_light_brown', label: 'Black w/ Light Brown' },
    { value: 'black_w_light_green', label: 'Black w/ Light Green' },
    { value: 'black_w_red', label: 'Black w/ Red' },
    { value: 'black_w_walnut_brown', label: 'Black w/ Walnut Brown' },
    { value: 'black_w_white', label: 'Black w/ White' },
    { value: 'blue_w_black', label: 'Blue w/ Black' },
    { value: 'blue_w_white', label: 'Blue w/ White' },
    { value: 'burgundy_w_white', label: 'Burgundy w/ White' },
    { value: 'green_w_white', label: 'Green w/ White' },
    { value: 'green_w_black', label: 'Green w/ Black' },
    { value: 'light_blue_w_white', label: 'Light Blue w/ White' },
    { value: 'light_brown_w_white', label: 'Light Brown w White' },
    { value: 'purple_w_white', label: 'Purple w/ White' },
    { value: 'red_w_black', label: 'Red w/ Black' },
    { value: 'red_w_white', label: 'Red w/ White' },
    { value: 'walnut_brown_w_black', label: 'Walnut Brown w/ Black' },
    { value: 'walnut_brown_w_dbl_wht', label: 'Walnut Brown w/ Dbl Wht' },
    { value: 'walnut_brown_w_white', label: 'Walnut Brown w/ White' },
    { value: 'white_antique', label: 'White (Antique)' },
    { value: 'white_w_black', label: 'White w/ Black' },
    { value: 'white_w_blue', label: 'White w/ Blue' },
    { value: 'white_w_burgundy', label: 'White w/ Burgundy' },
    { value: 'white_w_dbl_blk', label: 'White w/ Dbl Blk' },
    { value: 'white_w_dbl_brown', label: 'White w/ Dbl Brown' },
    { value: 'white_w_green', label: 'White w/ Green' },
    { value: 'white_w_light_brown', label: 'White w/ Light Brown' },
    { value: 'white_w_light_green', label: 'White w/ Light Green' },
    { value: 'white_w_red', label: 'White w/ Red' },
    { value: 'white_w_walnut_brown', label: 'White w/ Walnut Brown' }
];

export const LEATHER_COLOR_OPTIONS = [
    { value: 'black', label: 'Black' },
    { value: 'brown', label: 'Brown' },
    { value: 'red', label: 'Red' },
    { value: 'white', label: 'White' },
    { value: 'other', label: 'Other' }
];

// Add this export constant with the ring options
export const RING_TYPE_OPTIONS = [
    { value: 'accent_rings', label: 'Accent Rings' },
    { value: 'simple_inlays', label: 'Simple Inlays' },
    { value: 'intricate_inlays', label: 'Intricate Inlays' },
];
