/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 JMCC_Standard_Cue.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function JMCC_Standard_Cue(props) {
  const { nodes, materials } = useGLTF('/JMCC_Standard_Cue.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Ferrule.geometry} material={materials['White Phenolic']} position={[0.017, 97.833, -759.562]} rotation={[Math.PI / 2, 0, 0]} scale={[15, 941.157, 15]} />
      <mesh geometry={nodes.Shaft_Collar.geometry} material={materials['Black Phenolic JMCC']} position={[0, 97.833, 0]} rotation={[Math.PI / 2, 0, 0]} scale={[15, 736.5, 15]} />
      <mesh geometry={nodes.Shaft.geometry} material={materials['Carbon Fiber JMCC']} position={[0, 97.833, 6.804]} rotation={[Math.PI / 2, 0, 0]} scale={[15, 775.639, 15]} />
      <mesh geometry={nodes.Tip.geometry} material={materials['Black Phenolic JMCC']} position={[0.017, 97.833, -770.357]} rotation={[Math.PI / 2, 0, 0]} scale={[15, 827.78, 15]} />
      <mesh geometry={nodes.Shaft_Collar_Ring.geometry} material={materials['Azure Malachite']} position={[0, 97.833, -32.891]} rotation={[Math.PI / 2, 0, 0]} scale={[14.622, 600.002, 14.622]} />
      <mesh geometry={nodes.Butt_Cap.geometry} material={materials['Black Phenolic JMCC']} position={[0, 97.833, -36.13]} rotation={[Math.PI / 2, 0, 0]} scale={[15, 736.5, 15]} />
      <mesh geometry={nodes.Butt_Sleeve.geometry} material={materials['Amboyna Burl']} position={[-1.316, 98.479, 634.465]} rotation={[Math.PI / 2, 0, 0]} scale={[15, 1052.531, 15]} />
      <mesh geometry={nodes.Forearm.geometry} material={materials['Amboyna Burl']} position={[0, 97.833, -9.369]} rotation={[Math.PI / 2, 0, 0]} scale={[15, 819.596, 15]} />
      <mesh geometry={nodes.Handle.geometry} material={materials['Pig Black']} position={[0, 97.833, 74.957]} rotation={[Math.PI / 2, 0, 0]} scale={[15, 594.272, 15]} />
      <mesh geometry={nodes.Joint_Collar.geometry} material={materials['Black Phenolic JMCC']} position={[0, 97.833, 0]} rotation={[Math.PI / 2, 0, 0]} scale={[15, 736.5, 15]} />
      <mesh geometry={nodes.Joint_Collar_Ring.geometry} material={materials['Azure Malachite']} position={[0, 97.833, 4.456]} rotation={[Math.PI / 2, 0, 0]} scale={[15.127, 600.002, 15.127]} />
      <mesh geometry={nodes.Butt_Cap_Ring.geometry} material={materials['Azure Malachite']} position={[0, 97.833, 678.432]} rotation={[Math.PI / 2, 0, 0]} scale={[21.682, 600.002, 21.682]} />
      <mesh geometry={nodes.Handle_Ring_1.geometry} material={materials['Azure Malachite']} position={[0, 97.833, 574.85]} rotation={[Math.PI / 2, 0, 0]} scale={[21.093, 600.002, 21.093]} />
      <mesh geometry={nodes.Handle_Ring_2.geometry} material={materials['Azure Malachite']} position={[0, 97.833, 290.827]} rotation={[Math.PI / 2, 0, 0]} scale={[17.648, 600.002, 17.648]} />
      <mesh geometry={nodes.JMCC_Logo.geometry} material={materials['JMCC White Logo']} position={[0.182, 110.766, 686.798]} scale={[12.5, 1, 12.5]} />
      <mesh geometry={nodes.Joint_Pin.geometry} material={materials['Material.005']} position={[0, 97.833, -13.544]} rotation={[Math.PI / 2, 0, 0]} scale={[2.5, 0.832, 2.5]} />
      <mesh geometry={nodes.Bumper.geometry} material={materials['Composite Rubber']} position={[0, 97.833, 707.089]} rotation={[Math.PI / 2, 0, 0]} scale={[10, 1.768, 10]} />
      <mesh geometry={nodes.Diamond_1.geometry} material={materials['Azure Malachite']} position={[0, 114.122, 638.258]} rotation={[0, 0, Math.PI]} scale={[42.668, 2, 65.644]} />
      <mesh geometry={nodes.Diamond_2.geometry} material={materials['Azure Malachite']} position={[-13.518, 99.018, 638.258]} rotation={[0, 0, -Math.PI / 2]} scale={[42.668, 2, 65.644]} />
      <mesh geometry={nodes.Diamond_3.geometry} material={materials['Azure Malachite']} position={[0, 81.542, 638.258]} scale={[42.668, 2, 65.644]} />
      <mesh geometry={nodes.Diamond_4.geometry} material={materials['Azure Malachite']} position={[6.933, 99.018, 638.258]} rotation={[0, 0, -Math.PI / 2]} scale={[42.668, 2, 65.644]} />
      <mesh geometry={nodes.Long_Point_1.geometry} material={materials['Black Phenolic JMCC']} position={[0.145, 101.974, 315.461]} scale={[7, 1, 230]} />
      <mesh geometry={nodes.Long_Point_2.geometry} material={materials['Black Phenolic JMCC']} position={[-4.628, 98.245, 315.881]} rotation={[0, 0, -Math.PI / 2]} scale={[7.5, 1, 230]} />
      <mesh geometry={nodes.Long_Point_4.geometry} material={materials['Black Phenolic JMCC']} position={[0, 92.221, 315.946]} scale={[7.5, 1, 230]} />
      <mesh geometry={nodes.Long_Point_3.geometry} material={materials['Black Phenolic JMCC']} position={[7.137, 98.245, 315.629]} rotation={[0, 0, -Math.PI / 2]} scale={[7.5, 1, 230]} />
      <mesh geometry={nodes.Short_Point_1.geometry} material={materials['Black Phenolic JMCC']} position={[0.145, 101.974, 315.461]} scale={[7, 1, 160]} />
      <mesh geometry={nodes.Short_Point_2.geometry} material={materials['Black Phenolic JMCC']} position={[-4.628, 98.245, 315.881]} rotation={[0, 0, -Math.PI / 2]} scale={[7.5, 1, 160]} />
      <mesh geometry={nodes.Short_Point_4.geometry} material={materials['Black Phenolic JMCC']} position={[0, 92.221, 315.946]} scale={[7.5, 1, 160]} />
      <mesh geometry={nodes.Short_Point_3.geometry} material={materials['Black Phenolic JMCC']} position={[7.137, 98.245, 315.629]} rotation={[0, 0, -Math.PI / 2]} scale={[7.5, 1, 160]} />
    </group>
  )
}

useGLTF.preload('/JMCC_Standard_Cue.glb')
